apiVersion: v1
kind: Service
metadata:
  name: ass7-1-service
  labels:
    app: ass7-1
spec:
  selector:
    app: ass7-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

